service: graphql-fda

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 128
  timeout: 10


plugins:
  - serverless-offline

functions:
  graphql:
    handler: dist/index.graphqlHandler  # Point to compiled JS in dist folder
    events:
      - http:
          path: graphql
          method: post
          cors: true
build:
  esbuild:
    bundle: true
    target: node20
    platform: node
    sourcemap: true