service: gql-fda

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true

plugins:
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001
